<?php include __DIR__ . '/modal_detail_pesanan.php'; ?>
<?php include __DIR__ . '/modal_update_status.php'; ?>
<?php include __DIR__ . '/modal_class.php'; ?>
<?php include __DIR__ . '/modal_gallery.php'; ?>
<?php include __DIR__ . '/modal_category.php'; ?>
<?php include __DIR__ . '/modal_admin.php'; ?>
<?php include __DIR__ . '/modal_change_password.php'; ?>
<?php include __DIR__ . '/modal_instructor.php'; ?>
<?php include __DIR__ . '/modal_cert.php'; ?>
<?php include __DIR__ . '/modal_cert_template.php'; ?>
<?php include __DIR__ . '/modal_testimonial.php'; ?>
<?php include __DIR__ . '/modal_material.php'; ?>
<?php include __DIR__ . '/modal_quiz.php'; ?>
<?php include __DIR__ . '/modal_chatbot.php'; ?>
<?php include __DIR__ . '/modal_finance.php'; ?>
<?php include __DIR__ . '/modal_facilities.php'; ?>